### PR TITLE
main-to-patch1

### PR DESCRIPTION
**Pull request by itArnaudov**
patch 1 is 4x commits behind

### CODE REVIEW

**Review by itArnaudov — COMMENTED** [review]
ok

**Review by itArnaudov — COMMENTED** [review]
good

**Review by itArnaudov — COMMENTED** [review]
tested

**Review by itArnaudov — COMMENTED** [review]
alright

**Review by Ivan-CBRE — COMMENTED** [review]
nice

**Review by Ivan-CBRE — COMMENTED** [review]
fancy

**Review by Ivan-CBRE — COMMENTED** [review]
smitten

**Review by Ivan-CBRE — COMMENTED** [review]
good

**Pull request merged**
