### PR TITLE
It arnaudov profile info patch 1.3

### PR DESCRIPTION
**Pull request by itArnaudov**
v1.3

### CODE REVIEW

**Review by itArnaudov — COMMENTED** [review]
good

**Review by itArnaudov — COMMENTED** [review]
agree

**Review by itArnaudov — COMMENTED** [review]
approve

**Review by Ivan-CBRE — COMMENTED** [review]
accept

**Review by Ivan-CBRE — COMMENTED** [review]
nice

**Review by Ivan-CBRE — COMMENTED** [review]
well done.

**Pull request merged**
